### ISSUE TITLE
Operator don't reply to https requests

### ISSUE THREAD

**Issue by bclermont** [stashed/stash#1057]
I'm installing latest version of stash using helm chart.

So far, it's all default values, except the namespace is `stash` instead of `kube-system`. ( https://github.com/stashed/installer/pull/40/files)

And it seem that operator is stuck and can't reply to http request.
```console
$ kubectl -n stash exec -c operator -ti [PODNAME] /bin/sh
/ $ wget https://localhost:8443/
Connecting to localhost:8443 (127.0.0.1:8443)
wget: can't connect to remote host (127.0.0.1): Connection timed out
```

I can't turn on the live/ready probes as the pod will always be restarted and APIService* are never up:

```
status:
  conditions:
    - lastTransitionTime: '2020-02-28T15:14:11Z'
      message: >-
        failing or missing response from
        https://10.152.183.185:443/apis/admission.stash.appscode.com/v1alpha1:
        Get
        https://10.152.183.185:443/apis/admission.stash.appscode.com/v1alpha1:
        net/http: request canceled while waiting for connection (Client.Timeout
        exceeded while awaiting headers)
      reason: FailedDiscoveryCheck
      status: 'False'
      type: Available
```

**Comment by bclermont** [comment]
I did extra investigation, if:

```
apiserver:
  enableMutatingWebhook: false
  enableValidatingWebhook: false
```

it seem to works, or at least it don't hang like before.

these values are optional, but it's not very clear what it's used for.

it seem to be somewhat related to the fact that I run all this outside `kube-system` namespace.

I really don't like to run anything in `kube-system` unless it's low-level and required to run the k8s cluster, not perform higher levels operations such as perform backups.

**Comment by bclermont** [comment]
I just installed in `kube-system`:

```
apiserver:
  healthcheck:
    enabled: false	
enableAnalytics: false
```

and it just don't work, https call hang. So the only way to make it works is disable those webhooks.

I tried with my pull request for the helm chart https://github.com/stashed/installer/pull/40/files
and the official helm chart.

**Comment by bclermont** [comment]
after starting on a blank k8s cluster, it now install using official chart, this is how I found about #1059

**Comment by bclermont** [comment]
problem had been identified and it's not stash

**Comment by ikaruswill** [comment]
I'm facing the same issue. Though I can't afford to refresh my k8s cluster at the moment. 
My setup:
K3s v1.17.4+k3s1
8x armv7l SBCs
1x arm64 SBC

Deployed using official YAML steps via helm template with the additional value of
```
    pushgateway:
      tag: v1.2.0
    nodeSelector:
      beta.kubernetes.io/arch: arm
```
Steps taken:
1. helm template
1. kubectl apply -f stash
1. kubectl delete -f stash (as I forgot to set the pushgateway version for multi-arch)
1. helm template
1. kubectl apply -f stash
1. kubectl delete -f stash (Unschedulable due to nodeSelector)
1. Remove health check and amd64 nodeSelector
1. kubectl apply -f stash
1. Health-check fails, kubectl port-forward curl times out, kubectl exec wget times out

I'll try to reproduce it on a temporary cluster on a couple of spare nodes.
