### ISSUE TITLE
Revert the choices removing autobackup & related to enterprise

### ISSUE THREAD

**Issue by stevefan1999-personal** [stashed/stash#1183]
Hi.

I'm a little dev who would like to use Stash to backup my stateful data without too much hassle for my app. I loved that auto backup option as I can easily make backup configurations by adding annotations to Helm. Yet I see that in the latest release these nice features has been removed from community version and it is now included in enterprise version instead. 

As I'm just a small developer I clearly can't be looking up to use the enterprise version. Plus the code commits shows what you do hence making a fork and a patch to either remove license checker or making the auto backup free again easily. In another word the split is such a silly idea...

So I suggest that at least the community version will have what the last free open source features prior to becoming a source-available product now. Then some more exclusive enterprise features like webhook/cluster recovery can be private.

**Comment by hossainemruz** [comment]
Hi @stevefan1999-personal we understand your concern. As you are our existing user, we will like you to continue using Stash. Please, setup a short meeting [here](https://calendly.com/appscode/30min). We will love to discuss with you how we can make it happen.

**Comment by Hugome** [comment]
Hello,

Just to join @stevefan1999-personal in this request.

I'm using lot of appscode services (KubeDB, Stash, KubeVault. awesome project, by the way, most easy/stable service I ever use for database/backup/vault in a K8S env), and the sudden change in License in KubeDB/Stash made me afraid of updating. 

In KubeDB, I don't know what will happen to all the good functionality of KubeDB, does my MongDB replicaset will be entreprise only, because it's consider a "Clustering" ?

Of course you need to license some functionality your product, to be able to continue to live and it's perfectly normal.
But please don't forget your an open source project first, in the appscode website your proud to show "2000+" developers and "5000+" github stars, and you're right to show that, but don't forget some of these star/developers are passionate dev loving your stuff, and you need to not disappoint them for their issues/pull requests/..., don't ignore them to be gridy on your licensing (You will lost way more than some $/€/...).

Also your project are based on opensource soft (Redis/Postgres/Vault/...) they just offer difference codebase for theirs enterprise client (Not a free trial/non commercial licensing) with a good choices of enterprise features (Of course as a personal I don't need some LDAP/AD authentification or FIPS Compliant stuff). MongoDb gone way further than with their SSPL, because if you offer a mongodb hosting service you need to be open source (Point 13 of the license)

I never had a chance to contribute and hope one day I will, but not on a "PolyForm/AppsCode-Trial" license :)
 
Also based on you first official communication for theses change (https://blog.byte.builders/post/relicensing/) the AutoBackup should have been in the community edtion.
![](https://blog.byte.builders/post/relicensing/stash-feature-matrix.svg)

Thanks for your awesomes projects, please make the right choices.
Hugo

**Comment by eifelmicha** [comment]
> Hi @stevefan1999-personal we understand your concern. As you are our existing user, we will like you to continue using Stash. Please, setup a short meeting [here](https://calendly.com/appscode/30min). We will love to discuss with you how we can make it happen.

Hello Emruz Hossain,
i set up a meeting but nobody showed up ;-(

Regards,
Michael

**Comment by tamalsaha** [comment]
Just in case anyone following this thread, Michael, David and I had a 40-min meeting this morning. Somehow I thought the meeting was at 10:30am my time while it was setup at 10 am.

**Comment by davidhiendl** [comment]
@tamalsaha Thank you for taking the time to talk to us. I'm very glad that some of the decisions on the non-commercial license were reverted and I'm patiently awaiting the finalization of the pricing decisions.

**Comment by tamalsaha** [comment]
Based on user feedback, we have decided to reconsider the license for Stash. Going forward the Community Edition will include the core backup/recovery functionalities and be available for anyone to use for any purposes including commercial purposes under a new [AppsCode Community License](https://github.com/appscode/licenses/raw/1.0.0/AppsCode-Community-1.0.0.md).

You can find the pricing options for the Stash Enterprise Edition on the website: https://stash.run/pricing/ . Based on your feedback, we have added an `Indie` plan that offers the Enterprise license of Stash for individual developers and small shops who need the additional features of the Enterprise edition at a very reasonable price. 

We have released Stash v2020.09.16 with the updated license. The similar changes will be reflected in the upcoming release of KubeDB.

Thanks for using Stash & KubeDB! If you have any questions or want to purchase a license for Stash, please do not hesitate to email me tamal@appscode.com .

**Comment by MacroPower** [comment]
@tamalsaha Was this option removed at some point? I was looking into it for my personal cluster and found this thread. But it appears that the "Indie" plan is no longer on the page you linked.
