### ISSUE TITLE
BackupConfiguration docs lacks info about reference to Repository in another namespace

### ISSUE THREAD

**Issue by elcomtik** [stashed/stash#1469]
I read [blog](https://blog.byte.builders/post/stash-v2022.02.22/ ) and current [docs](https://stash.run/docs/v2022.07.09/concepts/crds/backupconfiguration/#specrepository) and didn't find info how to reference to Repository in another namespace.

It looks like it is not necessary to be defined. However, if the Repository is in another namespace, then BackupConfiguration will be in the notReady phase with RepositoryNotAvailable message. I found out that by trial & error, it can be defined by spec.repository.namespace key, so I think it should be added to docs.

**Comment by hossainemruz** [comment]
Check this doc: https://stash.run/docs/v2022.07.09/guides/managed-backup/dedicated-storage-namespace/

**Comment by elcomtik** [comment]
I've missed that guide. I'll read it and check if there's anything else I've missed.

Still reference docs for BackupConfiguration should contain this.

**Comment by sgielen** [comment]
I was also looking for this and couldn't find it anywhere!

Indeed, the docs explain about `spec.repository.name` and I just randomly decided to try `spec.repository.namespace` which worked. The docs are otherwise excellent and nicely specific, so the omission of `spec.repository.namespace` was quite a surprise :-)
