### ISSUE TITLE
Avoid logging `restic` output

### ISSUE THREAD

**Issue by tamalsaha** [stashed/stash#280]
I think we can just pass `restic` output to /dev/null. To show showing restic commands, we need to set `ShowCMD = false` https://github.com/appscode/stash/blob/321d741480afa422db8c9a07cfbbd863d51bca18/pkg/cli/restic.go#L31

ref: https://github.com/appscode/stash/issues/125#issuecomment-355435062

**Comment by whereisaaron** [comment]
The `restic` output is interactive stuff with line breaks galore and not ideal for logging. However. it's a hard choice, because I do like seeing the stats about files, size, and upload time. And if an error occurs you'd want to see the `stderr` output from restic. Maybe the command line echo and restic `stdout` output could be tied to the next up '-v' log level.

**Comment by asoltesz** [comment]
I need the exact opposite ATM.

My restore session does nothing and I would need to see more detailed restic logs about what files it restored, what file size...etc.

BTW: how do I configure such a detailed log level?

**Comment by hossainemruz** [comment]
>My restore session does nothing and I would need to see more detailed restic logs about what files it restored, what file size...etc.

@asoltesz You can describe the RestoreSession or view Stash operator log. That should indicate whats going on.

**Comment by asoltesz** [comment]
@hossainemruz my problem has been solved, it was a permission issue. 

Stash 0.9 now runs as non-root and my target container (pgadmin) runs as root. Stash/Restic simply didn't have access to the target folder that was in the possession of root.

Possibly, a more detailed Restic log could have told me what the issue was. However, I didn't see anything in the Restic/Stash container output logs that would have signified the problem. 

I have filed #1097 to better help with situations like this.
