### ISSUE TITLE
How to restore to given snapshot when multiple backups exist

### ISSUE THREAD

**Issue by LeoQuote** [stashed/stash#993]
If I have 5 backups for a deployment , when I create `RestoreSession`, which of it would be used ? what should I do if I want to use the second older backup ? 

possible related : #603

**Comment by hossainemruz** [comment]
If you specify `paths` section in `spec.rules` of `RestoreSession`, then Stash will restore the latest snapshot of this path. If you want to restore a specific snapshot, then specify `snapshots` field instead of `paths`.

Ref: https://appscode.com/products/stash/v0.9.0-rc.2/concepts/crds/restoresession/#spec-rules

This guide uses snapshot field for restoring a PVC: https://appscode.com/products/stash/v0.9.0-rc.2/guides/latest/volumes/pvc/

This guide will help you to know the available snapshots: https://appscode.com/products/stash/v0.9.0-rc.2/concepts/crds/snapshot/

**Comment by LeoQuote** [comment]
Thanks for your reply!
