### ISSUE TITLE
How to automatically restore when pod is restarted

### ISSUE THREAD

**Issue by segator** [stashed/stash#995]
I would like to convert somehow my pods to """stateless"""
for this will be nice if  stash can auto inject a initcontainer to restore the volume every time the pod restarts, so then my pod state can move between machines without need distributed storage.
I read something about workload initializer on old verisons, how can we do that now in latest 0.9?

Thanks!

**Comment by hossainemruz** [comment]
@segator We initially thought about supporting this use-case. Then, we decided not to support it because we wanted to make sure user has full control of restore process. Kubernetes is highly dynamic environment. Your pod can restart anytime even without your intention. So, restoring in each restart may lead to data loss. User can always restore by just creating a RestoreSession. If you really wan't such use case, just use an init-container. You can modify our stash init-container and remove the part that is responsible for skipping restore if a restore has been done already.

**Comment by segator** [comment]
Cann you tell me where i can find the code related to this init container?
Thanks

**Comment by hossainemruz** [comment]
This is the line of your interest: https://github.com/stashed/stash/blob/ec5c9efdbcbe588ce51b28ad69c191c198cda3c3/pkg/restore/restore.go#L177

Here is the restore `init-container` definition: https://github.com/stashed/stash/blob/ec5c9efdbcbe588ce51b28ad69c191c198cda3c3/pkg/util/init_container.go#L51

**Comment by segator** [comment]
Ok Thanks I will have a look ;)
